config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :venues
  resources :clients
  resources :providers
  resources :appointments

   root 'venues#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :venue
  has_and_belongs_to_many :providers

  validates_associated :venue
  validates :price, :duration, numericality: true
  validates :name, :duration, :price, :venue_id, presence: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
    @service.venue_id = params.require(:venue)
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:venue_id, :name, :description, :duration, :price)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @service.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h4>

      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :venue, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :venue, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :duration, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :duration, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/services/edit.html.erb
<div class="page-header">
  <%= link_to services_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @service, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing service</h1>
</div>

<%= render 'form' %>

app/views/services/index.html.erb
<div class="page-header">
  <%= link_to new_service_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Service
  <% end %>
  <h1>Listing services</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Venue</th>
            <th>Name</th>
            <th>Description</th>
            <th>Duration</th>
            <th>Price</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @services) do |service| %>
            <td><%= service.venue %></td>
            <td><%= service.name %></td>
            <td><%= service.description %></td>
            <td><%= service.duration %></td>
            <td><%= service.price %></td>
            <td><%= link_to 'Show', service %></td>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/services/new.html.erb
<div class="page-header">
  <%= link_to services_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New service</h1>
</div>

<%= render 'form' %>

app/views/services/show.html.erb
<div class="page-header">
  <%= link_to services_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_service_path(@service), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show service</h1>
</div>

<dl class="dl-horizontal">
  <dt>Venue:</dt>
  <dd><%= @service.venue %></dd>

  <dt>Name:</dt>
  <dd><%= @service.name %></dd>

  <dt>Description:</dt>
  <dd><%= @service.description %></dd>

  <dt>Duration:</dt>
  <dd><%= @service.duration %></dd>

  <dt>Price:</dt>
  <dd><%= @service.price %></dd>

</dl>