config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :venues
  resources :clients
  resources :providers
  resources :appointments

   root 'venues#index'

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  validates :phone, :cellphone, numericality: {only_integer: true}, length: {minimum: 7, maximum: 20}
  validates :email, format: /@/
  validates :name, :zip, :address, presence: true

  def phone=(phone)
    super(phone.gsub(/\D/, ''))
  end

  def cellphone=(cellphone)
    super(cellphone.gsub(/\D/, ''))
  end

  def zip=(zip)
    super(zip.gsub(/\D/, ''))
  end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show, :edit, :update, :destroy]

  # GET /venues
  # GET /venues.json
  def index
    @venues = Venue.all
  end

  # GET /venues/1
  # GET /venues/1.json
  def show
  end

  # GET /venues/new
  def new
    @venue = Venue.new
  end

  # GET /venues/1/edit
  def edit
  end

  # POST /venues
  # POST /venues.json
  def create
    @venue = Venue.new(venue_params)

    respond_to do |format|
      if @venue.save
        format.html { redirect_to @venue, notice: 'Venue was successfully created.' }
        format.json { render :show, status: :created, location: @venue }
      else
        format.html { render :new }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venues/1
  # PATCH/PUT /venues/1.json
  def update
    respond_to do |format|
      if @venue.update(venue_params)
        format.html { redirect_to @venue, notice: 'Venue was successfully updated.' }
        format.json { render :show, status: :ok, location: @venue }
      else
        format.html { render :edit }
        format.json { render json: @venue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venues/1
  # DELETE /venues/1.json
  def destroy
    @venue.destroy
    respond_to do |format|
      format.html { redirect_to venues_url, notice: 'Venue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venue
      @venue = Venue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venue_params
      params.require(:venue).permit(:name, :state, :city, :zip, :address, :email, :phone, :cellphone, :zapzap)
    end
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for(@venue, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @venue.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@venue.errors.count, "error") %> prohibited this venue from being saved:</h4>

      <ul>
      <% @venue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :phone, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :cellphone, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :cellphone, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zapzap, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :zapzap, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :address, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :city, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :state, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :state, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zip, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :zip, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/venues/edit.html.erb
<div class="page-header">
  <%= link_to venues_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @venue, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing venue</h1>
</div>

<%= render 'form' %>

app/views/venues/index.html.erb
<div class="page-header">
  <%= link_to new_venue_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Venue
  <% end %>
  <h1>Listing venues</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Cellphone</th>
            <th>Zapzap</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @venues) do |venue| %>
            <td><%= venue.name %></td>
            <td><%= venue.email %></td>
            <td><%= venue.phone %></td>
            <td><%= venue.cellphone %></td>
            <td><%= venue.zapzap %></td>
            <td><%= venue.address %></td>
            <td><%= venue.city %></td>
            <td><%= venue.state %></td>
            <td><%= venue.zip %></td>
            <td><%= link_to 'Show', venue %></td>
        <td><%= link_to 'Edit', edit_venue_path(venue) %></td>
        <td><%= link_to 'Destroy', venue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/venues/new.html.erb
<div class="page-header">
  <%= link_to venues_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New venue</h1>
</div>

<%= render 'form' %>

app/views/venues/show.html.erb
<div class="page-header">
  <%= link_to venues_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_venue_path(@venue), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show venue</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @venue.name %></dd>

  <dt>Email:</dt>
  <dd><%= @venue.email %></dd>

  <dt>Phone:</dt>
  <dd><%= @venue.phone %></dd>

  <dt>Cellphone:</dt>
  <dd><%= @venue.cellphone %></dd>

  <dt>Zapzap:</dt>
  <dd><%= @venue.zapzap %></dd>

  <dt>Address:</dt>
  <dd><%= @venue.address %></dd>

  <dt>City:</dt>
  <dd><%= @venue.city %></dd>

  <dt>State:</dt>
  <dd><%= @venue.state %></dd>

  <dt>Zip:</dt>
  <dd><%= @venue.zip %></dd>

</dl>